version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "qwerty"]
    environment:
      - REDIS_PASSWORD=qwerty

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
